# **Homework 2 - Subsetting**
Programmer name: Thanh Phan

#### **This programming focuses on using pandas to read and subset New York State's 2015 IRS tax data. Key metrics are calculated by the analysis and extracting specified tax variables into bespoke data subsets depending on particular income categories, it also engages in DataFrame modification.**

## **Academic Integrity Statement**
By submitting this code for grading, I confirm the following:

- that this is Notebook represents my own unique code created as a solution to the assigned problem.
- that this is Notebook was created specifically to satisfy the requirements detailed in this assignment.

Other than the textbook and material presented during our class sessions, I received help in designing and bebugging my code from the following people and/or websites:
1. None

In [133]:
#import the pandas library for data manipulation and analysis
import pandas as pd

In [134]:
# read the CSV file into a pandas DataFrame
df = pd.read_csv('C:\\Data Analysis Using Python\\homeworks\\HW2\\15zpnyagi.csv')

In [135]:
# Set pandas display options to show up to 150 columns without truncating them
pd.options.display.max_columns = 150

In [136]:
# display the first 5 rows of the DataFrame
df.head()

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,NUMDEP,TOTAL_VITA,VITA,TCE,VITA_EIC,RAL,RAC,ELDERLY,A00100,N02650,A02650,N00200,A00200,N00300,A00300,N00600,A00600,N00650,A00650,N00700,A00700,N00900,A00900,N01000,A01000,N01400,A01400,N01700,A01700,SCHF,N02300,A02300,N02500,A02500,N26270,A26270,N02900,A02900,N03220,A03220,N03300,A03300,N03270,A03270,N03150,A03150,N03210,A03210,N03230,A03230,N03240,A03240,N04470,A04470,A00101,N18425,A18425,N18450,A18450,N18500,A18500,N18300,A18300,N19300,A19300,N19700,A19700,N04800,A04800,N05800,A05800,N09600,A09600,N05780,A05780,N07100,A07100,N07300,A07300,N07180,A07180,N07230,A07230,N07240,A07240,N07220,A07220,N07260,A07260,N09400,A09400,N85770,A85770,N85775,A85775,N09750,A09750,N10600,A10600,N59660,A59660,N59720,A59720,N11070,A11070,N10960,A10960,N11560,A11560,N06500,A06500,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,36,NY,10001,1,3760,2910,360,400,2250,4690,890,250,130,120,70,0,490,840,42724,3760,44588,2470,31797,720,581,540,1336,500,840,110,94,1070,7444,470,571,230,1317,410,3092,0,130,659,140,377,160,398,1190,1864,0,0,0,0,130,454,40,170,190,188,60,197,0,0,310,4676,4320,170,464,110,52,160,845,290,1394,150,749,200,288,1550,9709,1480,1022,0,0,40,13,350,142,50,3,0,0,130,91,120,27,40,11,0,0,940,1193,150,412,150,362,180,47,3030,5961,1300,1984,910,1606,370,430,210,183,100,81,1300,880,2040,2158,0,0,0,0,750,766,2510,4418
1,36,NY,10001,2,2430,1790,240,330,1370,3270,640,130,60,70,0,0,310,430,90162,2430,92506,2050,72388,590,598,480,2030,460,1464,190,244,450,5971,430,1389,160,1479,290,4822,0,120,684,270,2119,150,1333,770,2344,40,10,20,176,110,496,90,429,330,369,20,68,0,0,510,8517,19380,400,1471,90,86,210,901,500,2485,190,972,380,804,2380,55177,2340,6991,0,0,80,62,710,652,150,50,100,61,240,302,170,32,220,198,20,8,340,1061,130,298,120,333,210,80,2290,10993,220,423,170,344,150,182,130,117,40,30,2180,6339,2240,7569,0,0,0,0,510,1187,1810,4285
2,36,NY,10001,3,1930,1520,200,150,1110,2450,330,0,0,0,0,0,170,350,119673,1930,121893,1720,99503,660,646,580,2366,550,1694,310,262,320,5422,510,1628,140,1548,220,5721,0,50,322,220,3660,130,1744,670,2220,40,9,20,301,80,417,90,385,330,406,40,77,0,0,760,11763,48140,680,3882,60,60,280,1215,750,5209,280,1326,580,1145,1920,89703,1910,14084,0,0,50,82,400,400,200,85,60,31,90,124,30,7,110,151,0,0,250,972,0,0,50,103,90,60,1880,17281,0,0,0,0,0,0,80,71,0,0,1890,13684,1910,14770,0,0,0,0,450,1397,1420,3574
3,36,NY,10001,4,1340,1070,160,70,770,1690,190,0,0,0,0,0,120,260,115820,1340,117209,1190,94945,560,916,480,2352,460,1819,410,404,220,3834,420,1856,140,1874,200,6893,0,30,150,170,3491,110,2625,300,1389,30,7,20,277,50,345,50,253,60,35,20,38,0,0,1050,17239,91210,1000,8167,40,42,300,1494,1050,9764,280,1764,720,1391,1320,90538,1320,16337,30,49,0,0,270,199,190,83,0,0,30,32,0,0,60,71,0,0,150,681,0,0,0,0,30,25,1310,19320,0,0,0,0,0,0,0,0,0,0,1320,16138,1330,16902,0,0,0,0,310,1209,980,3268
4,36,NY,10001,5,2480,1790,540,70,1520,3390,380,0,0,0,0,0,150,370,348440,2480,353017,2240,288378,1270,1976,1100,7137,1040,5372,1070,1678,430,14528,970,9293,220,5042,300,13216,0,60,291,260,6171,300,5506,590,4577,60,16,60,1340,120,979,100,570,60,53,0,0,0,0,2240,49979,317521,2180,30017,50,97,630,4108,2240,34445,580,4694,1520,3537,2470,282911,2470,59338,320,897,0,0,620,930,500,722,50,27,40,49,0,0,60,64,0,0,340,2179,0,0,0,0,60,87,2440,66370,0,0,0,0,0,0,30,29,0,0,2470,58408,2470,60809,110,28,40,42,560,3816,1770,7787

1. What is the total of “Salaries and wages amount” for all NY tax filers in 2015?

In [137]:
# select the A00200 (Salaries and Wages) column as a pandas Series 
df['A00200']

0         31797
1         72388
2         99503
3         94945
4        288378
         ...
9229     522783
9230     532819
9231     449583
9232    1022594
9233    4392280
Name: A00200, Length: 9234, dtype: int64

In [138]:
# Calculate the total sum of salaries and wages across all returns
total_salaries_and_wages=df['A00200'].sum()

In [139]:
# display the total salaries and wages amount
print(total_salaries_and_wages)

514823973

2. What is the total for "Educator expenses amount" in Washingtonville, NY (Zipcode 10992)?

In [140]:
# display the value of A03220 (educator expenses amount) for the rows where zipcode is 10992
df.loc[df['zipcode']==10992, 'A03220']

1206     6
1207     0
1208     6
1209     7
1210    33
1211     8
Name: A03220, dtype: int64

In [141]:
# Calculate the total sum of educator expenses for the rows where zipcode is 10992
total_educator_expenses_by_zipcode = df.loc[df['zipcode'] == 10992, 'A03220'].sum()

In [142]:
# display the total educator expenses for zipcode 10992
print(total_educator_expenses_by_zipcode)

60

3. What is the mean number of dependents claimed by all New York tax filers in the adjusted gross income range of $50,000 to $75,000? Display your answer using a meaningful print statement and a formatted numeric answer.

In [143]:
# Calculate the total number of dependents for the rows where agi_stub is 3 (income range of $50,000 to $75,000)
total_dependents = df.loc[df['agi_stub']==3,'NUMDEP'].sum()

In [144]:
# display the total number of dependents 
print(total_dependents)

684670

In [145]:
# Calculate the total number of returns for the rows where agi_stub is 3 (income range of $50,000 to $75,000)
total_tax_returns = df.loc[df['agi_stub']==3,'N1'].sum()

In [146]:
# display the total number of tax returns
print(total_tax_returns)

1275000

In [147]:
# Calculate the mean number of dependents for the rows where agi_stub is 3 (income range of $50,000 to $75,000)
mean_dependents = total_dependents / total_tax_returns

In [148]:
# display the mean number of dependents
print(f'The mean number of dependents claimed by all New York tax filers in the adjusted gross income range of $50,000 to $75,000 is {mean_dependents:.2f}')

The mean number of dependents claimed by all New York tax filers in the adjusted gross income range of $50,000 to $75,000 is 0.54

4. Create data frames that contain only the following subsets of the original dataset:

a. "df" - columns for zipcode, adjusted gross income category, number of exemptions, number of elderly returns, taxable Social Security benefits amount, and income tax amount.

In [149]:
# subset the DataFrame to include only the required columns
df = df[['zipcode', 'agi_stub', 'N2', 'ELDERLY', 'A02500', 'A06500']]

b. "df2" - the df columns plus the rows for only the lowest AGI category

In [150]:
# subset the DataFrame to include only the rows where agi_stub is 1 (income range of $1 to $25,000 aka lowest income range)
df2 = df.loc[df['agi_stub']==1]

Display the first 10 rows for the df data frame and the last 8 rows of the df2 data frame.

In [151]:
# display the first 10 rows of the subsetted DataFrame df
df.head(10)

   zipcode  agi_stub     N2  ELDERLY  A02500  A06500
0    10001         1   4690      840     377     880
1    10001         2   3270      430    2119    6339
2    10001         3   2450      350    3660   13684
3    10001         4   1690      260    3491   16138
4    10001         5   3390      370    6171   58408
5    10001         6   4220      250    3548  415672
6    10002         1  36580     4520     641    3187
7    10002         2  14590     1210    4210   18221
8    10002         3   7060      640    5900   31172
9    10002         4   3990      380    4720   31540

In [152]:
# display the last 8 rows of the subsetted DataFrame df2
df2.tail(8)

      zipcode  agi_stub     N2  ELDERLY  A02500  A06500
9186    14895         1   2460      460     209     385
9192    14897         1    200       30     118      25
9198    14898         1    520       70       0      55
9204    14901         1   4720      460     160     559
9210    14903         1   1760      300     101     355
9216    14904         1   5310      650     249     748
9222    14905         1   1870      360     139     299
9228    99999         1  44410     7060    2959    7543